### PR TITLE
Fix for #30

### LINKED ISSUE #30: Empty resultset returned when using $select within $expand, and no root $select
`{{base_url}}/api/posts?$expand=author($select=id),category`

I would expect this to produce 
```
[
    {
        "id": 1,
        "title": "Ultricies Sem Ltd",
        "text": "quam. Curabitur vel lectus. Cum",
        "author": {
            "id": 1
        },
        "category": {
            "id": 1,
            "name": "Eu Nulla Limited"
        }
    },
...
]
```

However, it produces an empty set `[]`. the reason being is because when we use `expand($select)` without giving a root select, the only thing that goes into the `queryBuilder.select()` is `authoir.id`. But since TypeORM requires you to select out the parent objects, it just kind of nullifies everything.

FWIW, the SQL generation works fine and returns the expected number of posts, but since we're not selecting the posts themselves, everything just gets thrown away

We might be able to fix it with the root table by simply adding all properties of the root entity to the select.

### PR DESCRIPTION
**Pull request by blitzmann**
Fixes #30 

### Pre-fix

`{{base_url}}/api/posts?$expand=author($select=id),category`

This would return an empty result set, primarily because we're not explicitly selecting out anything for the Post.

```
[]
```

### Post-fix
`{{base_url}}/api/posts?$expand=author($select=id),category`

Produces the expected response:
```
[
    {
        "id": 1,
        "title": "Ultricies Sem Ltd",
        "text": "quam. Curabitur vel lectus. Cum",
        "author": {
            "id": 1
        },
        "category": {
            "id": 1,
            "name": "Eu Nulla Limited"
        }
    },
...
]
```

### CODE REVIEW

File: src/lib/executeQuery.ts [hunk 1]
```diff
@@ -23,10 +23,17 @@ const queryToOdataString = (query): string => {
   return result;
 };
 
-const processIncludes = (queryBuilder: any, odataQuery: any, alias: string) => {
+const processIncludes = (queryBuilder: any, odataQuery: any, alias: string, parent_metadata: any): [any, string] =>  {
```
Comment (blitzmann) [inline src/lib/executeQuery.ts]: Technically, the metadata here isn't used yet, but it may be helpful in the future to have access to these properties. (for example, for the todo: `// todo: remove columns that are isSelect: false`).
